version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test -- --watchAll=false

      - run:
          name: Run SonarQube Analysis
          command: |
            npm install --save-dev sonarqube-scanner
            npx sonarqube-scanner \
              -Dsonar.projectKey=hein-van-niekerk_customer-portal \
              -Dsonar.organization=hein-van-niekerk \
              -Dsonar.sources=src \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build

