version: 2.1

jobs:
  build:
    docker:
      
-image: cimg/node:20.3.0
  steps:
-checkout
-run: npm ci
-run: npm test -- --watchAll=false,
-run:
  name: SonarQube Analysis
  command: |
    npm install --save-dev sonarqube-scanner
    npx sonarqube-scanner \
    -Dsonar.projectKey=my-project \
    -Dsonar.sources=src \
    -Dsonar.host.url=https://your-sonarqube-server.com/ \
    -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  scan_and_test:
    jobs:
      
-build
